// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWn_KW_ntHCfccfmvNSZuDxD21d_mq3zc',
    appId: '1:456660130247:web:aec776746c534a2f3861e2',
    messagingSenderId: '456660130247',
    projectId: 'mychatapp-60370',
    authDomain: 'mychatapp-60370.firebaseapp.com',
    storageBucket: 'mychatapp-60370.appspot.com',
    measurementId: 'G-K8LRQJ347L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdqJgNHZ7L82h6KGOAuuD8YHrHxZs9__Y',
    appId: '1:456660130247:android:f79dca82bb2af2933861e2',
    messagingSenderId: '456660130247',
    projectId: 'mychatapp-60370',
    storageBucket: 'mychatapp-60370.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBltiF3lt-iO9BefnnFlwsHKZJFn6mt_j8',
    appId: '1:456660130247:ios:6ca5563db2e6c6e63861e2',
    messagingSenderId: '456660130247',
    projectId: 'mychatapp-60370',
    storageBucket: 'mychatapp-60370.appspot.com',
    iosClientId: '456660130247-590l0pqfgdudea225ot26e0got61cmu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatapp',
  );
}
